name: Terraform Lint
on:
  # Trigger the workflow on push or pull request on the master branch only
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
