name: Terraform Checks
on:
  # Trigger the workflow on push or pull request on the master branch only
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'example/'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Terraform Validate
      #   uses: hashicorp/terraform-github-actions@master
      #   with:
      #     tf_actions_version: latest
      #     tf_actions_subcommand: 'validate'
      #     tf_actions_working_dir: '.'
      #     tf_actions_comment: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'example/'
          tf_actions_comment: true
          args: '-var=region="us-east-1"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
